-- 1. Create user_account table to store user credentials and registration time
CREATE TABLE user_account (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create food_category table to define categories for food items
CREATE TABLE food_category (
    category_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- 3. Create user_preference table to store app settings for each user
CREATE TABLE user_preference (
    preference_id SERIAL PRIMARY KEY,
    preference_key VARCHAR(255) NOT NULL,
    preference_value VARCHAR(255) NOT NULL,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES user_account(user_id)
);

-- 4. Create food table with a foreign key linking to food_category
CREATE TABLE food (
    -- fdc_id uses INT (not SERIAL) as it is assigned by the USDA FoodData Central API, not auto-generated by the database.
    fdc_id INT PRIMARY KEY,
    data_type VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES food_category(category_id)
);

-- 5. Create food_nutrient table to store nutritional values for foods
CREATE TABLE food_nutrient (
    food_nutrient_id SERIAL PRIMARY KEY,
    nutrient VARCHAR(255) NOT NULL,
    amount FLOAT,
    fdc_id INT,
    FOREIGN KEY (fdc_id) REFERENCES food(fdc_id)
);

-- 6. Create saved_comparison_food table to store users' saved food lists for comparison
CREATE TABLE saved_comparison_food (
    food_comparison_id SERIAL PRIMARY KEY,
    sort_order INT NOT NULL,
    fdc_id INT,
    FOREIGN KEY (fdc_id) REFERENCES food(fdc_id),
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES user_account(user_id)
);
